---
apiVersion: v1
kind: Service
metadata:
  name: app-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: $CI_ENVIRONMENT_SLUG
    service: app-$CI_ENVIRONMENT_SLUG
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    space: $KUBE_NAMESPACE
    track: stable
  annotations:
    app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: $CI_ENVIRONMENT_SLUG
      name: app-$CI_ENVIRONMENT_SLUG
      track: stable
      space: $KUBE_NAMESPACE
  template:
    metadata:
      labels:
        name: app-$CI_ENVIRONMENT_SLUG
        app: $CI_ENVIRONMENT_SLUG
        service: app-$CI_ENVIRONMENT_SLUG
        track: stable
        space: $KUBE_NAMESPACE
      annotations:
        app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
        app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
        build_id: "$CI_JOB_ID"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: app-$CI_ENVIRONMENT_SLUG
        image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            memory: "256Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /app/status.json
            port: 3000
            scheme: HTTP
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 10
        envFrom:
          - configMapRef:
              name: ${CI_PROJECT_NAME}-config
        env:
          - name: PROCESS
            value: "server:puma"
          {{SECRETS}}
      imagePullSecrets:
        - name: gitlab-registry
      nodeSelector:
        doks.digitalocean.com/node-pool: shared-dev-pool
