apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
  namespace: $KUBE_NAMESPACE
spec:
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-$CI_ENVIRONMENT_SLUG
            image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
            imagePullPolicy: "IfNotPresent"
            resources:
              requests:
                memory: "256Mi"
                cpu: "50m"
              limits:
                cpu: "100m"
                memory: "512Mi"
            envFrom:
              - configMapRef:
                name: ${CI_PROJECT_NAME}-config
            env:
              - name: PROCESS
                value: "app:cron"
              - name: CRON_TASK
                value: "-T"
              {{SECRETS}}
          restartPolicy: Never
          imagePullSecrets:
          - name: gitlab-registry
