---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    space: $KUBE_NAMESPACE
    track: stable
  annotations:
    app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: $CI_ENVIRONMENT_SLUG
      name: sidekiq-$CI_ENVIRONMENT_SLUG
      service: sidekiq-$CI_ENVIRONMENT_SLUG
      track: stable
  template:
    metadata:
      labels:
        name: sidekiq-$CI_ENVIRONMENT_SLUG
        app: $CI_ENVIRONMENT_SLUG
        service: sidekiq-$CI_ENVIRONMENT_SLUG
        track: stable
        space: $KUBE_NAMESPACE
      annotations:
        build_id: "$CI_JOB_ID"
        app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
        app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: sidekiq-$CI_ENVIRONMENT_SLUG
        image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "750"
            memory: "768Mi"
          requests:
            memory: "512Mi"
            cpu: "100m"
        envFrom:
          - configMapRef:
              name: ${CI_PROJECT_NAME}-config
        env:
          - name: PROCESS
            value: "server:sidekiq"
          {{SECRETS}}
      imagePullSecrets:
        - name: gitlab-registry
      nodeSelector:
        doks.digitalocean.com/node-pool: shared-dev-pool
