---
apiVersion: v1
kind: Service
metadata:
  name: static-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: $CI_ENVIRONMENT_SLUG
    service: static-$CI_ENVIRONMENT_SLUG
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    service: static-$CI_ENVIRONMENT_SLUG
    space: $KUBE_NAMESPACE
    track: stable
  annotations:
    app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: $CI_ENVIRONMENT_SLUG
      name: static-$CI_ENVIRONMENT_SLUG
      service: static-$CI_ENVIRONMENT_SLUG
      track: stable
  template:
    metadata:
      labels:
        name: static-$CI_ENVIRONMENT_SLUG
        app: $CI_ENVIRONMENT_SLUG
        service: static-$CI_ENVIRONMENT_SLUG
        track: stable
        space: $KUBE_NAMESPACE
      annotations:
        build_id: "$CI_JOB_ID"
        app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
        app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: static-$CI_ENVIRONMENT_SLUG
        image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            memory: "32Mi"
            cpu: "50m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 10
        env:
          - name: PROCESS
            value: "server:nginx"
          {{SECRETS}}
      imagePullSecrets:
        - name: gitlab-registry
      nodeSelector:
        doks.digitalocean.com/node-pool: shared-dev-pool
