---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "2G"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
spec:
  rules:
  - host: $CI_ENVIRONMENT_HOSTNAME
    http:
      paths:
      - path: /
        backend:
          serviceName: app-$CI_ENVIRONMENT_SLUG
          servicePort: 80
      - path: /assets
        backend:
          serviceName: static-$CI_ENVIRONMENT_SLUG
          servicePort: 80
      - path: /images
        backend:
          serviceName: static-$CI_ENVIRONMENT_SLUG
          servicePort: 80
      - path: /(android-chrome-192x192.png|android-chrome-512x512.png|apple-touch-icon.png|apple-touch-icon-precomposed.png|browserconfig.xml|favicon-16x16.png|favicon-32x32.png|favicon.ico|fb-share.png|fb-share.jpg|mstile-150x150.png|robots.txt|safari-pinned-tab.svg|site.webmanifest)
        backend:
          serviceName: static-$CI_ENVIRONMENT_SLUG
          servicePort: 80

  - host: www.change-me
    http:
      paths:
      - path: /
        backend:
          serviceName: app-$CI_ENVIRONMENT_SLUG
          servicePort: 80
      - path: /assets
        backend:
          serviceName: static-$CI_ENVIRONMENT_SLUG
          servicePort: 80
      - path: /images
        backend:
          serviceName: static-$CI_ENVIRONMENT_SLUG
          servicePort: 80
      - path: /(android-chrome-192x192.png|android-chrome-512x512.png|apple-touch-icon.png|apple-touch-icon-precomposed.png|browserconfig.xml|favicon-16x16.png|favicon-32x32.png|favicon.ico|fb-share.png|fb-share.jpg|mstile-150x150.png|robots.txt|safari-pinned-tab.svg|site.webmanifest)
        backend:
          serviceName: static-$CI_ENVIRONMENT_SLUG
          servicePort: 80
  tls:
  - hosts:
    - $CI_ENVIRONMENT_HOSTNAME
    secretName: web-${CI_ENVIRONMENT_SLUG}-cert
  - hosts:
    - www.change-me
    - change-me
    secretName: www-change-me-cert
